version: '3.11.4'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_management_container
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: inventory_db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
    db:

networks:
  task_network:
    external: true