version: '3.11.4'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_management_container
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${db_name}
      - POSTGRES_USER=${db_user}
      - POSTGRES_PASSWORD=${db_password}

volumes:
    db: